name: CI - PodSage App

on:
  push:
    branches: [ master ]
  pull_request:

env:
  APP_DIR: podsage/app
  TESTS_DIR: podsage/tests

jobs:
  test-app:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r $APP_DIR/requirements.txt
          pip install pytest httpx

      - name: Show current directory and contents
        run: |
          pwd
          ls -la

      - name: Run tests
        run: |
          print $TESTS_DIR/test_app_health.py
          pytest $TESTS_DIR/test_app_health.py

      # Optional: Slack notification if test fails
      - name: Notify Slack on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: '#FF0000'
          SLACK_MESSAGE: |
            🚨 PodSage CI failed on ${{ github.repository }} @ ${{ github.ref }}
            Commit: ${{ github.event.head_commit.message }}
            Author: ${{ github.actor }}
